export const actions = {
  SET_ACTIVE_TAB: 'SET_ACTIVE_TAB',
  SET_WINDOW_SIZE: 'SET_WINDOW_SIZE',
  SET_TRANSCRIPTIONS: 'SET_TRANSCRIPTIONS'
};

export const activeTabs = {
  NEW: 'NEW',
  TRANSCRIPTIONS: 'TRANSCRIPTIONS',
  SETTINGS: 'SETTINGS'
};
