export const actions = {
  SET_ACTIVE_TAB: 'SET_ACTIVE_TAB',
  SET_WINDOW_SIZE: 'SET_WINDOW_SIZE',
  SET_TRANSCRIPTIONS: 'SET_TRANSCRIPTIONS',
  SET_ACCESS_KEY_ID: 'SET_ACCESS_KEY_ID',
  SET_SECRET_ACCESS_KEY: 'SET_SECRET_ACCESS_KEY',
  SET_UPLOADING: 'SET_UPLOADING',
  SET_FILTER: 'SET_FILTER',
  SET_FILTER_TYPE: 'SET_FILTER_TYPE',
  SET_APPLIED_FILTER: 'SET_APPLIED_FILTER',
  SET_VOCABULARY: 'SET_VOCABULARY',
  SET_VOCABULARY_FILTER: 'SET_VOCABULARY_FILTER',
  SET_APPLIED_VOCABULARY_FILTER: 'SET_APPLIED_VOCABULARY_FILTER',
  SET_UPDATING_VOCABULARY_LIST: 'SET_UPDATING_VOCABULARY_LIST',
  SET_SELECTED_WORDS: 'SET_SELECTED_WORDS'
};

export const activeTabs = {
  NEW: 'NEW',
  TRANSCRIPTIONS: 'TRANSCRIPTIONS',
  SETTINGS: 'SETTINGS',
  VOCABULARY: 'VOCABULARY'
};

export const localStorageKeys = {
  TEMP_OBJ: 'TEMP_OBJ',
  ACCESS_KEY_ID: 'ACCESS_KEY_ID',
  SECRET_ACCESS_KEY: 'SECRET_ACCESS_KEY',
  UPDATED_VOCABULARY_LIST: 'UPDATED_VOCABULARY_LIST'
};

export const aws = {
  REGION: 'us-east-2',
  BUCKET: 'transcriber.temp.bucket'
};

export const transcriptionStatuses = {
  UNKNOWN: 'UNKNOWN',
  PROCESSING: 'PROCESSING',
  READY: 'READY',
  FAILED: 'FAILED'
};

export const filterTypes = {
  TITLE: 'TITLE',
  CONTENTS: 'CONTENTS'
};

export const CUSTOM_VOCAB_NAME = 'CUSTOM_VOCAB';
